import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/constants/app_constants.dart';
import '../../../core/providers/order_provider.dart';
import '../../../core/providers/auth_provider.dart';
import '../widgets/order_card.dart';
import 'host_tracking_screen.dart';
import '../../../core/services/review_service.dart';
import '../../../core/models/review_model.dart';
import '../../common/widgets/rating_dialog.dart';

class HostOrdersScreen extends StatefulWidget {
  const HostOrdersScreen({super.key});

  @override
  State<HostOrdersScreen> createState() => _HostOrdersScreenState();
}

class _HostOrdersScreenState extends State<HostOrdersScreen>
    with SingleTickerProviderStateMixin {
  late TabController _tabController;

  @override
  void initState() {
    super.initState();
    _tabController = TabController(length: 2, vsync: this);

    WidgetsBinding.instance.addPostFrameCallback((_) {
      final authProvider = context.read<AuthProvider>();
      if (authProvider.user != null) {
        context.read<OrderProvider>().loadOrdersByHost(authProvider.user!.id);
      }
    });
  }

  @override
  void dispose() {
    _tabController.dispose();
    super.dispose();
  }

  void _showRateVendorDialog(BuildContext context, dynamic order) {
    showDialog(
      context: context,
      builder: (context) => RatingDialog(
        title: 'Rate Vendor',
        message: 'How was your experience with ${order.vendorName}?',
        onSubmit: (rating, comment) async {
          final authProvider = context.read<AuthProvider>();
          final user = authProvider.user;
          if (user == null) return;

          final review = ReviewModel(
            id: '', // Generated by service
            orderId: order.id,
            reviewerId: user.id,
            reviewerName: user.name,
            revieweeId: order.vendorId,
            revieweeRole: 'vendor',
            rating: rating,
            comment: comment,
            createdAt: DateTime.now(),
          );

          await ReviewService.submitReview(review);

          if (mounted) {
            ScaffoldMessenger.of(context).showSnackBar(
              const SnackBar(
                content: Text('Review submitted successfully!'),
                backgroundColor: AppColors.success,
              ),
            );
            // Reload orders to update UI
            context.read<OrderProvider>().loadOrdersByHost(user.id);
          }
        },
      ),
    );
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title:
            const Text('My Orders', style: TextStyle(color: AppColors.primary)),
        bottom: TabBar(
          controller: _tabController,
          labelColor: AppColors.primary,
          unselectedLabelColor: AppColors.textSecondary,
          indicatorColor: AppColors.primary,
          tabs: const [
            Tab(text: 'Active'),
            Tab(text: 'Completed'),
          ],
        ),
      ),
      body: Consumer<OrderProvider>(
        builder: (context, orderProvider, child) {
          return TabBarView(
            controller: _tabController,
            children: [
              _buildOrdersList(orderProvider.activeOrders, isCompleted: false),
              _buildOrdersList(orderProvider.completedOrders,
                  isCompleted: true),
            ],
          );
        },
      ),
    );
  }

  Widget _buildOrdersList(List orders, {required bool isCompleted}) {
    if (orders.isEmpty) {
      return Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          children: [
            const Text('📦', style: TextStyle(fontSize: 60)),
            const SizedBox(height: 16),
            Text(
              'No orders yet',
              style: Theme.of(context).textTheme.titleMedium,
            ),
            const SizedBox(height: 8),
            Text(
              'Your orders will appear here',
              style: Theme.of(context).textTheme.bodyMedium?.copyWith(
                    color: AppColors.textSecondary,
                  ),
            ),
          ],
        ),
      );
    }

    return ListView.builder(
      padding: const EdgeInsets.all(16),
      itemCount: orders.length,
      itemBuilder: (context, index) {
        final order = orders[index];
        final bool showRateButton = isCompleted &&
            order.status == AppConstants.statusDelivered &&
            !order.isVendorReviewed;

        return Padding(
          padding: const EdgeInsets.only(bottom: 16),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              OrderCard(
                order: order,
                onTap: () {
                  if (order.status != AppConstants.statusDelivered &&
                      order.status != AppConstants.statusCancelled) {
                    Navigator.of(context).push(
                      MaterialPageRoute(
                        builder: (_) => HostTrackingScreen(order: order),
                      ),
                    );
                  }
                },
              ),
              if (showRateButton) ...[
                const SizedBox(height: 8),
                Align(
                  alignment: Alignment.centerRight,
                  child: ElevatedButton.icon(
                    onPressed: () => _showRateVendorDialog(context, order),
                    icon: const Icon(Icons.star_rate, size: 18),
                    label: const Text('Rate Vendor'),
                    style: ElevatedButton.styleFrom(
                      backgroundColor: Colors.amber,
                      foregroundColor: Colors.white,
                      shape: RoundedRectangleBorder(
                        borderRadius: BorderRadius.circular(20),
                      ),
                    ),
                  ),
                ),
              ],
            ],
          ),
        );
      },
    );
  }
}
